
services:
  pocketprofits:
    image: gitmotion/pocketprofits:latest
    # build: .
    container_name: pocketprofits
    restart: unless-stopped
    ports:
      - ${POCKETPROFITS_PORT:-3000}:3000
    volumes:
      - ${POCKETPROFITS_DATA_PATH:-./data}:/app/data
    environment:
      - POCKETPROFITS_PIN=${POCKETPROFITS_PIN:-} # PIN to access the site
      - BASE_URL=${POCKETPROFITS_BASE_URL:-http://localhost:3000} # URL to access the site
      - CURRENCY=${POCKETPROFITS_CURRENCY:-USD} # Supported Currency Codes:
      - SITE_TITLE=${POCKETPROFITS_SITE_TITLE:-POCKETPROFITS} # Name to show on site
      - INSTANCE_NAME=${POCKETPROFITS_INSTANCE_NAME:-} # Name of instance/account
      # (OPTIONAL)
      # Restrict origins - ex: https://subdomain.domain.tld,https://auth.proxy.tld,http://internalip:port' (default is '*')
      # - ALLOWED_ORIGINS=${POCKETPROFITS_ALLOWED_ORIGINS:-http://localhost:3000}
    # healthcheck:
    #   test: wget --spider -q  http://127.0.0.1:3000
    #   start_period: 20s
    #   interval: 20s
    #   timeout: 5s
    #   retries: 3