name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE: gitmotion/pocketprofits
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set Docker tags
        id: docker_meta
        run: |
          TAGS="${{ env.DOCKER_IMAGE }}:${{ github.sha }}"
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            TAGS+=" ${{ env.DOCKER_IMAGE }}:latest"
          elif [ "${{ github.ref }}" = "refs/heads/testing" ]; then
            TAGS+=" ${{ env.DOCKER_IMAGE }}:testing"
          fi
          echo "DOCKER_TAGS=$TAGS" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build -t ${{ env.DOCKER_IMAGE }}:${{ github.sha }} .

      - name: Tag with latest (on main branch push)
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag ${{ env.DOCKER_IMAGE }}:${{ github.sha }} ${{ env.DOCKER_IMAGE }}:latest

      - name: Push Docker images
        run: |
          docker push ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            docker push ${{ env.DOCKER_IMAGE }}:latest
          fi
