name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE: gitmotion/pocketprofits
  GHCR_IMAGE: ghcr.io/gitmotion/pocketprofits
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set Docker tags
        id: docker_meta
        run: |
          TAGS="${{ env.DOCKER_IMAGE }}:${{ github.sha }}"
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            TAGS+=" ${{ env.DOCKER_IMAGE }}:latest"
          elif [ "${{ github.ref }}" = "refs/heads/testing" ]; then
            TAGS+=" ${{ env.DOCKER_IMAGE }}:testing"
          fi
          echo "DOCKER_TAGS=$TAGS" >> $GITHUB_ENV

      - name: Build and Push Multi-Platform Image
        run: |
          docker buildx create --use
          docker buildx build --platform ${{ env.PLATFORMS }} \
            --tag ${{ env.DOCKER_IMAGE }}:${{ github.sha }} \
            --tag ${{ env.DOCKER_IMAGE }}:latest \
            --tag ${{ env.GHCR_IMAGE }}:${{ github.sha }} \
            --tag ${{ env.GHCR_IMAGE }}:latest \
            --push .