name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE: gitmotion/pocketprofits
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set Docker tags
        id: docker_meta
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "DOCKER_TAGS=${DOCKER_IMAGE}:latest" >> $GITHUB_ENV
          elif [ "${{ github.ref }}" = "refs/heads/testing" ]; then
            echo "DOCKER_TAGS=${DOCKER_IMAGE}:testing" >> $GITHUB_ENV
          fi

      - name: Build Docker Image
        run: |
          docker build -t ${{ env.DOCKER_TAGS }} .

      - name: Push Docker Image
        run: |
          docker push ${{ env.DOCKER_TAGS }} 